### PR TITLE
reorganize & cleanup

### LINKED ISSUE #14: Julia packages
Opening this issue to discuss how to best handle Julia packages with `conda`.

### LINKED ISSUE #67: Warning related to JULIA_PKGDIR seen during update
Issue: julia returned a warning during my most recent conda update.

Here's the warning returned to my console:

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: | ERROR: KeyError: key "JULIA_PKGDIR"                                                           $
Stacktrace:
 [1] (::getfield(Base, Symbol("##418#419")))(::String) at ./                                                           $
 [2] access_env at ./env.jl:45 [inlined]
 [3] getindex(::Base.EnvDict, ::String) at ./env.jl:76
 [4] top-level scope at none:0

WARNING conda.core.link:run_script(818): pre-unlink script f                                                           $
consider notifying the package maintainer                |   Updating registry at `~/.julia/registries/Gene            $
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
    Fetching: [>                                        ]  0.0 %
    Resolving Deltas: [==============================>          ]  72.5 %
 Resolving package versions...
                                                                                                         do            $

```

Environment (<code>conda list</code>):

```
$ conda list

# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom           py36hbbc8b67_0
anaconda-client           1.7.1                      py_0    conda-forge
anaconda-project          0.8.2                      py_1    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
arpack                    3.6.3           blas_openblash77d739c_2  [blas_openblas]  conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astroid                   2.1.0                 py36_1000    conda-forge
astropy                   3.1.1            py36h470a237_0    conda-forge
atk                       2.25.90              h05f3006_1    conda-forge
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
automat                   0.7.0                      py_1    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.os              0.1.1                 py36_1000    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
bcftools                  1.9                  h4da6232_0    bioconda
beautifulsoup4            4.7.0                 py36_1000    conda-forge
bedtools                  2.27.1               he941832_2    bioconda
bitarray                  0.8.3            py36h470a237_0    conda-forge
bkcharts                  0.2                      py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
blaze                     0.11.3                   py36_0    conda-forge
bleach                    3.0.2                      py_1    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.15.1               hfc679d8_0    conda-forge
bokeh                     1.0.3                 py36_1000    conda-forge
boto                      2.49.0                     py_0    conda-forge
boto3                     1.9.72                     py_0    conda-forge
botocore                  1.12.73                    py_0    conda-forge
bottleneck                1.2.1            py36h7eb728f_1    conda-forge
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12              h276e583_5    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.1                      py_0    conda-forge
constantly                15.1.0                     py_0    conda-forge
contextlib2               0.5.5                      py_2    conda-forge
cryptography              2.2.1            py36hdffb7b8_1    conda-forge
cryptography-vectors      2.4.2                   py_1000    conda-forge
curl                      7.63.0               h74213dd_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.2           py36hfc679d8_0    conda-forge
cytoolz                   0.9.0.1          py36h470a237_1    conda-forge
dask                      1.0.0                      py_0    conda-forge
dask-core                 1.0.0                      py_0    conda-forge
datashape                 0.5.4                    py36_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
deeptools                 3.1.3            py36h470a237_0    bioconda
defusedxml                0.5.0                      py_1    conda-forge
distributed               1.25.1                py36_1000    conda-forge
docutils                  0.14                  py36_1001    conda-forge
emacs                     26.1                 h5d2cb88_0    conda-forge
entrypoints               0.2.3                 py36_1002    conda-forge
et_xmlfile                1.0.1                    py36_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fastcache                 1.0.2            py36h470a237_1    conda-forge
fftw                      3.3.8                h470a237_1    conda-forge
filelock                  3.0.10                     py_0    conda-forge
flask                     1.0.2                      py_2    conda-forge
flask-cors                3.0.7                      py_0    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
fribidi                   1.0.5                h470a237_0    conda-forge
gdk-pixbuf                2.36.12              h4ab6910_1    conda-forge
gensim                    3.5.0                    py36_0    conda-forge
get_terminal_size         1.0.0                haa9412d_0
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
gevent                    1.3.7            py36h470a237_0    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
glob2                     0.6                        py_0    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gmpy2                     2.0.8            py36hb705a9b_2    conda-forge
gnutls                    3.6.5                ha0399c4_1    conda-forge
gobject-introspection     1.56.1           py36haaf12d0_1    conda-forge
graphite2                 1.3.13               hfc679d8_0    conda-forge
greenlet                  0.4.13                   py36_0    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h5856ed1_0    conda-forge
gtk2                      2.24.31              hde048ef_0    conda-forge
h5py                      2.9.0            py36he5c79e1_0    conda-forge
harfbuzz                  1.9.0                h04dbb29_1    conda-forge
hdf5                      1.10.4          nompi_h5598ddc_1105    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
homer                     4.9.1           pl526h2d50403_6    bioconda
html5lib                  1.0.1                      py_0    conda-forge
htslib                    1.9                  hc238db4_4    bioconda
hyperlink                 17.3.1                     py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.8                   py36_1000    conda-forge
imageio                   2.4.1                 py36_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        0.6                      py36_0    conda-forge
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2019.1                      144
ipykernel                 5.1.0           py36h24bf2e0_1001    conda-forge
ipython                   7.2.0           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                 py36_1000    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jbig                      2.1               h470a237_1001    conda-forge
jdcal                     1.4                        py_1    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
jeepney                   0.4                        py_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
julia                     1.0.3           blas_openblash977ebb0_0  [blas_openblas]  conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.4                   py36_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
keyring                   17.1.1                py36_1000    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
lazy-object-proxy         1.3.1            py36h470a237_0    conda-forge
libcurl                   7.63.0               hbdb9355_0    conda-forge
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libevent                  2.0.22               hdffb7b8_2    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libgit2                   0.27.7               h5ee2e84_0    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libopenblas               0.2.20               h9ac9557_7
libpng                    1.6.36               ha92aebf_0    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libssh2                   1.8.0                h5b517e9_3    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.10               he6b73bb_1    conda-forge
libtool                   2.4.6                h470a237_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
libxslt                   1.1.32               h88dbc4e_2    conda-forge
llvmlite                  0.26.0           py36hd28b015_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.2.5            py36hc9114bc_0    conda-forge
lzo                       2.10                 h470a237_0    conda-forge
markupsafe                1.1.0            py36h470a237_0    conda-forge
matplotlib                3.0.2            py36h8a2030e_1    conda-forge
matplotlib-base           3.0.2            py36h20b835b_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
metis                     5.1.0                hfc679d8_3    conda-forge
mistune                   0.8.4            py36h470a237_0    conda-forge
mkl                       2019.1                      144
mkl-service               1.1.2            py36h651fb7a_4
mkl_fft                   1.0.10                   py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
more-itertools            4.3.0                 py36_1000    conda-forge
mpc                       1.1.0                hb705a9b_6    conda-forge
mpfr                      4.0.1                h16a7912_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.0            py36h2d50403_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_2    conda-forge
nettle                    3.4.1                h470a237_2    conda-forge
networkx                  2.2                        py_1    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
notebook                  5.7.4                 py36_1000    conda-forge
numba                     0.41.0           py36hf8a1672_0    conda-forge
numexpr                   2.6.9            py36hf8a1672_0    conda-forge
numpy                     1.15.4          py36_blas_openblashb06ca3d_0  [blas_openblas]  conda-forge
numpy-base                1.14.3           py36h0ea5e3f_1
numpydoc                  0.8.0                      py_1    conda-forge
oauthlib                  2.1.0                      py_0    conda-forge
odo                       0.5.1                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3                ha44fe06_1    conda-forge
openlibm                  0.5.4                h470a237_0    conda-forge
openpyxl                  2.5.12                     py_0    conda-forge
openspecfun               0.5.3                h26a2512_0    conda-forge
openssl                   1.0.2p               h470a237_2    conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4           py36hf8a1672_0    conda-forge
pandoc                    2.5                           0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14              he752989_2    conda-forge
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
patchelf                  0.9                  hfc679d8_2    conda-forge
path.py                   11.5.0                     py_0    conda-forge
pathlib2                  2.3.3                 py36_1000    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pcre2                     10.23                         2    conda-forge
pep8                      1.7.1                      py_0    conda-forge
perl                      5.26.2               h470a237_0    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    5.4.0            py36hc736899_0    conda-forge
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
pkginfo                   1.4.2                      py_1    conda-forge
plotly                    3.4.2                      py_0    conda-forge
pluggy                    0.8.0                      py_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
psutil                    5.4.8            py36h470a237_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
py                        1.7.0                      py_0    conda-forge
py2bit                    0.3.0                    py36_1    bioconda
pyasn1                    0.4.4                      py_1    conda-forge
pyasn1-modules            0.2.3                      py_0    conda-forge
pybigwig                  0.3.12           py36hdfb72b2_2    bioconda
pycodestyle               2.4.0                      py_1    conda-forge
pycosat                   0.6.3            py36h470a237_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pycrypto                  2.6.1            py36h470a237_2    conda-forge
pycurl                    7.43.0.2         py36hb7f436b_0
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pylint                    2.2.2                 py36_1000    conda-forge
pyodbc                    4.0.24           py36hfc679d8_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.6.0            py36h8210e8a_8    conda-forge
pyrsistent                0.14.8           py36h470a237_0    conda-forge
pysam                     0.15.1           py36h0380709_0    bioconda
pysocks                   1.6.8                 py36_1002    conda-forge
pytables                  3.4.4            py36h72a6d90_4    conda-forge
pytest                    4.0.2                 py36_1000    conda-forge
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.4.0                      py_0    conda-forge
pytest-doctestplus        0.1.3                      py_0    conda-forge
pytest-openfiles          0.3.1                      py_0    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
python                    3.6.7                h5001a0f_1    conda-forge
python-crfsuite           0.9.6            py36h2d50403_0    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
pywavelets                1.0.1            py36h7eb728f_0    conda-forge
pyyaml                    3.13             py36h470a237_1    conda-forge
pyzmq                     17.1.2           py36hae99301_1    conda-forge
qt                        5.6.2               h679f5bc_11    conda-forge
qtawesome                 0.5.5              pyh8a2030e_0    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
qtpy                      1.5.2              pyh8a2030e_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.21.0                py36_1000    conda-forge
requests-oauthlib         1.0.0                      py_1    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rope                      0.10.7                     py_1    conda-forge
ruamel_yaml               0.15.71          py36h470a237_0    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
samtools                  1.9                  h8ee4bcc_1    bioconda
scikit-image              0.14.1           py36hfc679d8_3    conda-forge
scikit-learn              0.20.2          py36_blas_openblash00c3548_400  [blas_openblas]  conda-for             ge
scipy                     1.2.0           py36_blas_openblashb06ca3d_200  [blas_openblas]  conda-for             ge
seaborn                   0.9.0                      py_0    conda-forge
secretstorage             3.1.0                 py36_1001    conda-forge
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py36_1000    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
smart_open                1.7.1                      py_0    conda-forge
snappy                    1.1.7                hfc679d8_2    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcollections         1.0.1                      py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sphinx                    1.8.3                 py36_1000    conda-forge
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.3.2                 py36_1001    conda-forge
spyder-kernels            0.3.0                 py36_1001    conda-forge
sqlalchemy                1.2.15           py36h470a237_0    conda-forge
sqlite                    3.26.0               hb1c47c0_0    conda-forge
statsmodels               0.9.0            py36h7eb728f_0    conda-forge
suitesparse               4.5.6           blas_openblash697e320_201  [blas_openblas]  conda-forge
sympy                     1.3                   py36_1000    conda-forge
tbb                       2019.3               h2d50403_0    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
tmux                      2.7                  hc78d2af_3    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
tqdm                      4.28.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
twisted                   18.9.0           py36h470a237_0    conda-forge
twython                   3.7.0                      py_0    conda-forge
typed-ast                 1.1.1            py36h470a237_0    conda-forge
umap-learn                0.3.7                 py36_1000    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unixodbc                  2.3.7                h09ba92c_0    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.10.11          py36h470a237_1    conda-forge
wurlitzer                 1.0.2                 py36_1000    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.1.2                      py_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xorg-fixesproto           5.0                  h470a237_2    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxaw               1.0.13               h470a237_2    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxfixes            5.0.3                h470a237_4    conda-forge
xorg-libxft               2.3.2                h7c24a56_3    conda-forge
xorg-libxmu               1.1.2                h470a237_2    conda-forge
xorg-libxpm               3.5.12               h470a237_2    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-libxt                1.1.5                h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_6    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
zope                      1.0                      py36_1
zope.interface            4.6.0            py36h470a237_0    conda-forge
```

Details about  <code>conda</code> and system ( <code>conda info</code> ):

```
$ conda info

     active environment : bioinfo
    active env location : /home/bioinfo/.conda/envs/bioinfo
            shell level : 2
       user config file : /home/bioinfo/.condarc
 populated config files : /home/bioinfo/.condarc
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.6.8.final.0
       base environment : /usr/local/bin/miniconda3  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/local/bin/miniconda3/pkgs
                          /home/bioinfo/.conda/pkgs
       envs directories : /home/bioinfo/.conda/envs
                          /usr/local/bin/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.6.8 Linux/3.10.0-957.1.3.el7.x86_64 rhel/7.6 glibc/2.17
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

### LINKED ISSUE #138: pre-unlink.sh and juliarc.jl are out of date
pre-unlink.sh and juliarc.jl are out of date

pre-unlink.sh refers to `JULIA_PKGDIR` which has been replaced by `JULIA_DEPOT_PATH`
`juliarc.jl` should be now be `~/.julia/config/startup.jl` since Julia v0.7

Going forward the best way to manage conda environments and julia environments would to create a new top-level shared julia environment for each conda environment. This has become easier with certain command line changes:

https://docs.julialang.org/en/v1/NEWS/#Command-line-option-changes

### PR DESCRIPTION
**Pull request by ngam**
Closes #67 
Closes #14 
Closes #140 
Closes #87 
Closes #160 
Closes #138 
Closes #76 

TODO:
- [x] isolate julia inside conda
- [x] sync julia project with conda env
- [x] stack julia envs

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
Supersedes #140

**Comment by ngam** [comment]
@mkitti feel free to review and merge. Or let me know if there are other cleanup/organization things we should deal with first. We should also move this to the other branch (v1.6.5) once we settle on a procedure. 

Should we expand the tests above?

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
These pass just fine locally: `# all except stdlib, add "opaque_closure", "filesystem" with 1.7`

**Comment by ngam** [comment]
Okay, all look good --- will test the stdlib as well soon

**Comment by mkitti** [comment]
Do we have parallelization in place yet?

**Comment by ngam** [comment]
> Do we have parallelization in place yet?

Not yet. I have enabled all tests in the last commit --- we will see how far this will go (my local machine exited with OOM). Then, the last thing after that will be to set `ncores=ceil(Int, Sys.CPU_THREADS` instead of the default (?) `ncores=ceil(Int, Sys.CPU_THREADS / 2`

**Comment by ngam** [comment]
Okay, I think this is it for this PR. The full test suite fails in random places, so we reverting back to the original list except adding new ones for v1.7 and increasing threads.

**Comment by ngam** [comment]
@mkitti review/merge when you have a chance. Increasing threads makes the linux_64_ build finish in 50 mins as opposed to 75 mins.

**Comment by mkitti** [comment]
I'm thinking of making a run at either setting a conda environment specific `JULIA_DEPOT_PATH` or at least setting `JULIA_PROJECT` ala #87 .

I wonder if downstream users have an opinion on this, @valeriupredoi ?

See also https://github.com/ESMValGroup/ESMValTool/issues/2419

**Comment by ngam** [comment]
Two questions:

1. Do you want to do that part of this PR or another PR? We could squeeze it here for sure
2. As only a beginner Julia user, could you explain to me which option would basically make julia a sub env of the conda env? I believe from a zoomed out view, I think this should be our first default --- set up julia (and everything associated with it) inside the conda env and have julia not interact too much with the outside system (especially, say, another installation of julia somewhere)

**Comment by mkitti** [comment]
That would be JULIA_DEPOT_PATH environment variable. That controls the DEPOT_PATH variable in Julia: https://docs.julialang.org/en/v1/base/constants/#Base.DEPOT_PATH

Essentially that would change the location of ~/.julia .

**Comment by ngam** [comment]
Okay, so if we want to move `~/.julia` to `$PREFIX/etc/.julia`, do we just set `JULIA_DEPOT_PATH` to be `$PREFIX/etc/` via `export JULIA_DEPOT_PATH="$PREFIX/etc/:$JULIA_DEPOT_PATH"`?

Then, does that take care of unsetting `/usr/local/share/julia` and `/usr/share/julia`?

**Comment by ngam** [comment]
Also, do you have preference if it is
`export JULIA_DEPOT_PATH="$CONDA_PREFIX/share/julia/site:$JULIA_DEPOT_PATH"`
vs
`export JULIA_DEPOT_PATH="$CONDA_PREFIX/etc/julia:$JULIA_DEPOT_PATH"` or
`export JULIA_DEPOT_PATH="$CONDA_PREFIX/etc/.julia:$JULIA_DEPOT_PATH"`

**Comment by ngam** [comment]
(feel free to edit my branch btw as you see fit)

**Comment by mkitti** [comment]
If `JULIA_DEPOT_PATH` is undefined, then you will get `$CONDA_PREFIX/share/julia/site:`. Julia will interpret the trailing `:` as meaning to append the default `DEPOT_PATH`. This could be useful.

```
(base) $ JULIA_DEPOT_PATH="" julia -E "DEPOT_PATH"
String[]
(base) $ JULIA_DEPOT_PATH=":" julia -E "DEPOT_PATH"
["/home/mkitti/.julia", "/home/mkitti/src/julia-1.6.0/local/share/julia", "/home/mkitti/src/julia-1.6.0/share/julia"]
(base) $ JULIA_DEPOT_PATH="$CONDA_PREFIX/share/julia/site:" julia -E "DEPOT_PATH"
["/home/mkitti/anaconda3/share/julia/site", "/home/mkitti/.julia", "/home/mkitti/src/julia-1.6.0/local/share/julia", "/home/mkitti/src/julia-1.6.0/share/julia"]
(base) $ JULIA_DEPOT_PATH="$CONDA_PREFIX/share/julia/site" julia -E "DEPOT_PATH"
["/home/mkitti/anaconda3/share/julia/site"]
```

**Comment by mkitti** [comment]
Do we need something like https://github.com/conda-forge/openjdk-feedstock/blob/57916550977ace39ff53885556d8ee5a30bf254a/recipe/build.sh#L181-L187 ?

Then we have activate.sh
```
export JULIA_DEPOT_PATH_BACKUP=${JULIA_DEPOT_PATH:-}
export JULIA_PROJECT_BACKUP=${JULIA_PROJECT:-}
export JULIA_DEPOT_PATH="$CONDA_PREFIX/share/julia/site:$JULIA_DEPOT_PATH"
export JULIA_PROJECT="$CONDA_PREFIX/share/julia/site/environments/$CONDA_DEFAULT_ENV"
```

and deactivate.sh:
```
export JULIA_DEPOT_PATH=$JULIA_DEPOT_PATH_BACKUP
export JULIA_PROJECT=$JULIA_PROJECT_BACKUP
unset JULIA_DEPOT_PATH_BACKUP
unset JULIA_PROJECT_BACKUP

if [ -z $JULIA_DEPOT_PATH ]; then
    unset JULIA_DEPOT_PATH
fi
if [ -z $JULIA_PROJECT ]; then
    unset JULIA_PROJECT
fi
```

maybe we should just merge #87 into here and see what happens?

**Comment by mkitti** [comment]
If I recall there were some minor test failures. Perhaps we just need to patch the tests?

**Comment by ngam** [comment]
> If I recall there were some minor test failures. Perhaps we just need to patch the tests?

We will see. This latest merge from mjohnson541:keep-julia-local-to-conda-env shouldn't introduce anything substantial in terms of tests, but we will see soon.

**Comment by ngam** [comment]
We have some tests failing...

**Comment by ngam** [comment]
@mkitti, I believe the tests fail because of this: 
```
export JULIA_PROJECT="$CONDA_PREFIX/share/julia/site/environments/$CONDA_DEFAULT_ENV"
```

Why are we hardwiring an environment here? Doesn't julia start with its own default env?

**Comment by ngam** [comment]
The other test fails because it basically points to home:

```
expanded == readchomp(setenv(`$exename -e 'println(Base.active_project())'`, "JULIA_PROJECT" => "@foo", "HOME" => homedir()))
```

**Comment by mkitti** [comment]
Julia starts with its own major version specific environment. In this case, I think we want a project specific environment which may be independent of major version.

**Comment by mkitti** [comment]
I agree the test is flawed. We should patch it and upstream it.

**Comment by mkitti** [comment]
Why are we using $CONDA_DEFAULT_ENV above?

**Comment by ngam** [comment]
> CONDA_DEFAULT_ENV

I think the original idea was to superficially sync the conda and julia envs. 

> I agree the test is flawed. We should patch it and upstream it.

I am tinkering with it now, I will try to figure out whatever julia's equivalent of $CONDA_PREFIX is and set that instead of home. However, I think the test is fundamentally broken, but I can be reading it wrong...

**Comment by mkitti** [comment]
I just misunderstood the meaning of `$CONDA_DEFAULT_ENV`. I guess that just means the current conda environment...

**Comment by mkitti** [comment]
I think we just need to pass `JULIA_DEPOT_PATH` through:

```julia
expanded == readchomp(setenv(`$exename -e 'println(Base.active_project())'`, "JULIA_PROJECT" => "@foo", "HOME" => homedir(), "JULIA_DEPOT_PATH" => ENV["JULIA_DEPOT_PATH"]))
```

**Comment by ngam** [comment]
Yes! I will commit soon

**Comment by mkitti** [comment]
> Yes! I will commit soon

Good. I'm getting myself a bit confused. It's possible this is fixed upstream.

**Comment by mkitti** [comment]
About ILP64, see https://julialang.org/blog/2021/11/julia-1.7-highlights/#libblastrampoline_mkljl

**Comment by mkitti** [comment]
Let's see what comes out of https://github.com/JuliaLang/julia/pull/43560 first, but this is looking good.

**Comment by mkitti** [comment]
@conda-forge-admin, please restart ci

**Comment by ngam** [comment]
> Let's see what comes out of [JuliaLang/julia#43560](https://github.com/JuliaLang/julia/pull/43560) first, but this is looking good.

The `addenv` alone won't cut it here because we are not running all tests. I mean --- I am sorry, that's a crazy hot garbage going up upstream in terms of testing. I will refix the my patches later today and we should merge.

I stand by my suggested edit here https://github.com/JuliaLang/julia/pull/43560#discussion_r775324245: adding ` "JULIA_DEPOT_PATH" => "$(Base.DEPOT_PATH[1])"` at the end of this call to ensure the correct point. 

And no, we don't need a `JULIA_PROJECT` --- we should just let julia decide whatever their default will be (v1.7) and the user can do whatever they want with that.

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
The reason we should define `JULIA_PROJECT` is that from the Julia perspective all the default environments will look like the generic base environment. The user will have no clue that they are actually in an environment that is encapsulated within their conda environment until they really interrogate it.

**Comment by mkitti** [comment]
Running External
  Programs

**Comment by ngam** [comment]
I see, but we never do that with anything else in conda. We also have the release tagline.

My understanding is that julia from conda should pretty much look identical as julia proper in a standalone installation. The only difference we are trying to achieve here is to _isolate_ julia (at least initially) within a conda environment. The other big difference is that we are relying on the system (read conda) to source some of the important dependencies instead of building them. Neither of these two will necessitate we predefine a specific env for the user. 

If you insist on presetting it, we will need to fix two tests or so. It's likely some tests are hardcoded upstream that need to be relaxed. Again though, I just don't think this is needed or will make a difference beyond making a mess of this solution. Since we haven't had any community engagement, you'll be the one to decide this 😉 so let me know what you want

**Comment by mkitti** [comment]
@conda-forge-admin, please restart ci

**Comment by ngam** [comment]
> @conda-forge-admin, please restart ci

Won't rereun the tests because with your latest addition of `addenv` it passed, so it won't repeat it unless something else changes.

**Comment by ngam** [comment]
Oh, something may be wrong with the CI actually --- see: https://github.com/conda-forge/julia-feedstock/pull/159

**Comment by ngam** [comment]
I can test the addition of JULIA_PROJECT locally. Should I focus on that?

**Comment by mkitti** [comment]
The easiest way around the tests would probably be to do something like
```
julia --project -e 'delete!(ENV,"JULIA_PROJECT"); Base.runtests( ... )`
```

The `--project` will set the project to the default project, overriding the environmental variable. The `delete!(ENV,"JULIA_PROJECT")` will clear the environmental variable, so subsequent sub-processes do not inherit it.

**Comment by ngam** [comment]
> The easiest way around the tests would probably be to do something like
> 
> ```
> julia --project -e 'delete!(ENV,"JULIA_PROJECT"); Base.runtests( ... )`
> ```
> 
> The `--project` will set the project to the default project, overriding the environmental variable. The `delete!(ENV,"JULIA_PROJECT")` will clear the environmental variable, so subsequent sub-processes do not inherit it.

But see, we can just drop these tests then. We should be testing for our particular case, where we have a new path and all, so that's why I didn't like the PR fix upstream because it still circumvents the legit test by going home again --- I would rather we tweak the test to address our own use case rather than circumventing them. The tests are there for a reason after all...

**Comment by mkitti** [comment]
Well, we can try to patch it again, but the game is similar to the other issue.

The first test that fails is
https://github.com/JuliaLang/julia/blob/ac5cc99908d463582e66db3368b9b48fae1e2525/test/loading.jl#L671-L684
```julia
mktempdir() do dir
    vdir = Base.DEFAULT_LOAD_PATH[2]
    vdir = replace(vdir, "#" => VERSION.major, count = 1)
    vdir = replace(vdir, "#" => VERSION.minor, count = 1)
    vdir = replace(vdir, "#" => VERSION.patch, count = 1)
    vdir = vdir[2:end] # remove @
    vpath = joinpath(dir, "environments", vdir)
    mkpath(vpath)
    withenv("JULIA_DEPOT_PATH" => dir) do
        script = "@assert startswith(Base.active_project(), $(repr(vpath)))"
        @test success(`$(Base.julia_cmd()) --startup-file=no -e $(script)`)
    end
end
```

This could probably be modified such that `withenv` includes `JULIA_PROJECT`.
```julia
        mktempdir() do dir
           vdir = Base.DEFAULT_LOAD_PATH[2]
           vdir = replace(vdir, "#" => VERSION.major, count = 1)
           vdir = replace(vdir, "#" => VERSION.minor, count = 1)
           vdir = replace(vdir, "#" => VERSION.patch, count = 1)
           vdir = vdir[2:end] # remove @
           vpath = joinpath(dir, "environments", vdir)
           mkpath(vpath)
           withenv("JULIA_DEPOT_PATH" => dir, "JULIA_PROJECT" => "") do
               script = "@assert startswith(Base.active_project(), $(repr(vpath)))"
               @test success(`$(Base.julia_cmd()) --startup-file=no -e $(script)`)
           end
       end
```

**Comment by ngam** [comment]
@mkitti let's shelve predefining a project for now. We can revisit in another round. I have serious reservations about the logic of adding it.

**Comment by mkitti** [comment]
Once we merge this, I would not want to mess with the environment variables again until Julia 1.8.

Looking at my own `~/.julia`, which is 48 GB at the moment, I would much prefer to have a distinct `JULIA_PROJECT` per conda environment rather than an entirely new `JULIA_DEPOT_PATH` per conda environment. Having a `JULIA_DEPOT_PATH` per conda environment will just end up being too duplicative, especially in terms of artifacts. It will also make working with `dev`ed packages a bit troublesome.

There are some good reasons to have a distinct `JULIA_DEPOT_PATH` per conda environment at the moment (e.g. [PyCall.jl](https://github.com/JuliaPy/PyCall.jl)), but those are issues that are better resolved elsewhere in the long term.

I'm testing a modified `JULIA_PROJECT` and `JULIA_LOAD_PATH` in #160. What I think we should do is bring a commented out version of that to the activate.sh and deactivate.sh here, so that individual users can select that configuration if desired.

**Comment by ngam** [comment]
@mkitti sounds good, this is definitely at the edge of comfort --- I am not familiar with how this works in practice. I will try to offer my zoomed out perspective in the other PR; specifically, there are few concerns I'd us to address (ideally add tests for) before we merge.

**Comment by ngam** [comment]
Also, one more thing: How does this impact creating _additional_ julia envs inside a specific conda env?

> I would much prefer to have a distinct JULIA_PROJECT per conda environment rather than an entirely new JULIA_DEPOT_PATH per conda environment

**Comment by mkitti** [comment]
The standard way to develop *packages* in Julia is to checkout their git trees in `$JULIA_DEPOT_PATH/dev`. For example, on this Linux box, I have the following packages in development.

```julia
$ ls ~/.julia/dev
BioformatsLoader  HDF5                  JLD       OpenCL        Spark            TaskWorkers
Demo              ImageTransformations  JProxies  RootTaskREPL  SpecialMatrices  Xnumber
FunctionRunner    Interpolations        Matcha    SHbundle      Sugar
GR                JavaCall              Napari    SnoopCompile  Taro
```

Users are highly encouraged to write packages rather than scripts. Packages are just Julia modules that are contained with Julia project environments. That is each package has their own Project.toml and Manifest.toml, although usually only Project.toml is distributed for libraries. One of the reasons packages are encouraged is that they are the basic precompilable unit. This precompilation is put in `$JULIA_DEPOT_PATH/compiled`.

As I mentioned above, each package is a Julia project. I can activate a package's project.

**Comment by ngam** [comment]
> I'm testing a modified `JULIA_PROJECT` and `JULIA_LOAD_PATH` in #160. What I think we should do is bring a commented out version of that to the activate.sh and deactivate.sh here, so that individual users can select that configuration if desired.

@mkitti, I will leave this up to you. Please review, edit, and merge as you find most fit (and don't forget the LTS PR #159). If something goes wrong, we will be able to initiate another round of edits. But I trust this is pretty good development. We will also be hearing from people.

**Comment by mkitti** [comment]
I think we should finish this one before addressing 1.6 LTS. I'm reluctant to making a breaking change to a patch release per semantic versioning and changing the JULIA_DEPOT_PATH will break setups.

Depots also stack in Julia, but I do not have a lot of experience with that.

**Comment by ngam** [comment]
> I think we should finish this one before addressing 1.6 LTS. I'm reluctant to making a breaking change to a patch release per semantic versioning and changing the JULIA_DEPOT_PATH will break setups.

Do you want to keep this open until we get another minor update then?

> Once we merge this, I would not want to mess with the environment variables again until Julia 1.8.

What's their rough dev cycle upstream? When would you expect 1.7.2 and 1.8.0 to arrive?

**Comment by ngam** [comment]
Do we have any other lingering issues that we should address btw? I saw some issues in this repo about packages but in my short testing, everything is working just fine. Basically, we have a complete julia 1.7.1 here that is equivalent to standalone installation, right?

(I am not talking about OS builds --- windows, arm, etc. will be a whole other hassle, that I am happy to work through in the next few weeks)

**Comment by mkitti** [comment]
1.7.2 is probably weeks to a few months away. 1.7.0 and 1.7.1 were separated by three weeks.

1.8.0 is likely 6 months to a year away.

File: recipe/build.sh [hunk 1]
```diff
@@ -6,6 +6,9 @@ export LIBRARY_PATH=${PREFIX}/lib
 export CMAKE_PREFIX_PATH=${PREFIX}
 export PATH="${PREFIX}/bin:${PATH}"
 
+#set JULIA_DEPOT_PATH in conda env
+export JULIA_DEPOT_PATH="${PREFIX}/share/julia/site:$JULIA_DEPOT_PATH" 
+
```
Comment (mkitti) [inline recipe/build.sh:11]: This should be removed.

**Review by mkitti — CHANGES_REQUESTED** [review]
Why are we keeping the old juliarc.jl and pre-unlink.sh around?

Is there any functionality in pre-unlink.sh that should be replicate?

File: recipe/build.sh (hunk 1 above)
Comment (ngam) [reply recipe/build.sh]: Done.

**Comment by mkitti** [comment]
I'm good to merge this if you are, @ngam .

**Comment by ngam** [comment]
Should we address #161 or wait?

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
It's great to see the rapid improvements coming in here! Big steps forward on many fronts.

But if you want a bit more community engagement you might want to consider slowing down just a little bit. This PR, which closes 7 issues, some of which have been around for a long time and have been opened and worked upon by other people, took all of 5 days from creation to merging. Over the Christmas days.
Still, I don't want to dampen the enthusiasm; it really is great to see this move forward.


For now, I have two concerns/comments:

The issue of separate depots for separate environments is really all about binary compatibility. Basically, anything that has been compiled for one environment cannot reliably be used with another environment because linked libraries may have changed in an ABI incompatible way (cf the recent libunwind problems, but I would expect this with a number of libraries, e.g. for I/O of special file formats like netCDF) and the compilers themselves may be different. If compiled bits are shared, this will lead to surprising segfaults in the future. This kind of problem is not likely to show up in tests that use similar environments created at roughly the same time, but is virtually guaranteed if very different environments with library overlap are used, particularly when those environments are created a long time apart.
To me, it is not clear to what degree compiled bits are an integral part of the Julia depots, but this is my main problem with `~/.julia` currently (i.e. conda-forge Julia <=1.6).

My second concern is that it is not completely clear to me to what degree this PR really addresses the issues it closes. For example, #14 is about packaging Julia packages for conda-forge, i.e. how should I create the conda-forge feedstock `julia-rainfarm` from https://github.com/jhardenberg/RainFARM.jl. While sorting out the depot paths certainly helps and might be necessary, from reading this PR I still don't know how to do this or where to look up the documentation. In terms of documentation, at a minimum I would expect a bullet point in the [enumeration for new packages](https://conda-forge.org/docs/maintainer/adding_pkgs.html#getting-started).
This is probably beyond the scope of this PR, but in that case we might want to keep #14 open for now.

**Comment by ngam** [comment]
> But if you want a bit more community engagement you might want to consider slowing down just a little bit. This PR, which closes 7 issues, some of which have been around for a long time and have been opened and worked upon by other people, took all of 5 days from creation to merging. Over the Christmas days.

Yeah, sorry... But, I'd rather interested people (like yourself) come back and reopen the issues and explain their current needs/expectations. It's very difficult for us to guess what people were thinking about 4+ years ago especially as the ecosystems (julia as well as conda) have moved so much since then. Obviously, we couldn't address all concerns (and you bring up really important ones) --- to help us push forward, could you please reopen issues/PRs that you think weren't adequately addressed and add your perspective?

I will start by opening two issues based on your two main concerns and we will work --- together and less rapidly --- to address them. 

> To me, it is not clear to what degree compiled bits are an integral part of the Julia depots, but this is my main problem with ~/.julia currently (i.e. conda-forge Julia <=1.6).

For this, @mkitti was of the opinion that we shouldn't change anything in the 1.6.x and just bring all newer changes to 1.7.1+. I concurred with his view (we don't want to mess up the setups of people who got comfortable with those versions...)

**Comment by ngam** [comment]
> My second concern is that it is not completely clear to me to what degree this PR really addresses the issues it closes. For example, #14 is about packaging Julia packages for conda-forge, i.e. how should I create the conda-forge feedstock `julia-rainfarm` from https://github.com/jhardenberg/RainFARM.jl

I certainly didn't read it this way. I am not sure if this is even applicable now that julia has their own ecosystem and package-building setup. Our real goal here was to better isolate julia inside conda envs, so that a user can have many different julias (via conda) and also a separate standalone julia smoothly. How the user ends up using such isolation is obviously none of our business, right? And I am not sure if we should pursue changes to actually enmesh julia and conda more tightly; again, my thinking/perspective was to better isolate them for each other (not vice versa). But that's just one single opinion and I am happy to discuss this further and work on bringing changes/improvements you'd like to see :)

**Comment by ngam** [comment]
> 7 issues

only 3. The others are PRs.

**Comment by mkitti** [comment]
Native machine code is not cached by Julia during normal operation, so I do not expect there to be be ABI issues for compiled code generated from Julia unless one is making direct a`ccall`s. What is cached is lowered code and type inference on a per Julia environment basis in `$JULIA_DEPOT/compiled`. That said this does change between Julia versions and is under active development.

Thr chosen defaults for the 1.7 releases are quite conservative with unique Julia depots and environments for each conda environment. My concern is actually that is too conservative and that we are duplicating too many things.

The use of PackageCompiler.jl, which actually involves native code generation and storage is another matter, but its location of the generated system image shared library is determined by the user.

**Comment by zklaus** [comment]
Thanks for your replies, @ngam and @mkitti. I'll pick up the discussion in #14, #164 and possibly new issues as needed.
